services:
  mysql_pagespeed:
    image: mysql:8.4.5
    container_name: mysql_pagespeed
    restart: always
    command: 
      - "--mysql-native-password=ON" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagespeed_db  
      MYSQL_USER: devcharlie
      MYSQL_PASSWORD: devcharlie
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      

  airflow-init:
    image: apache/airflow:2.7.0-python3.10
    depends_on:
      - mysql_pagespeed
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql://devcharlie:devcharlie@mysql_pagespeed:3306/pagespeed_db
      PAGESPEED_API_KEY: ${PAGESPEED_API_KEY}
      TARGET_URL: ${TARGET_URL}
    entrypoint: >
      bash -c "
        airflow db init &&
        airflow users create
          --username devcharlie 
          --password Tony00642! 
          --firstname Charlie 
          --lastname Dev 
          --role Admin 
          --email devcharlie2698619@gmail.com
      "
    volumes:
      - ../dags:/opt/airflow/dags
      - ../plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - airflow_logs:/opt/airflow/logs

  airflow:
    image: apache/airflow:2.7.0-python3.10
    container_name: airflow
    restart: always
    depends_on:
      - mysql_pagespeed
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql://devcharlie:devcharlie@mysql_pagespeed:3306/pagespeed_db
      PAGESPEED_API_KEY: ${PAGESPEED_API_KEY}
      TARGET_URL: ${TARGET_URL}
      AIRFLOW__SMTP__SMTP_HOST: ${AIRFLOW__SMTP__SMTP_HOST}
      AIRFLOW__SMTP__SMTP_STARTTLS: ${AIRFLOW__SMTP__SMTP_STARTTLS}
      AIRFLOW__SMTP__SMTP_SSL: ${AIRFLOW__SMTP__SMTP_SSL}
      AIRFLOW__SMTP__SMTP_PORT: ${AIRFLOW__SMTP__SMTP_PORT}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${AIRFLOW__SMTP__SMTP_MAIL_FROM}
      AIRFLOW__SMTP__SMTP_USER: ${AIRFLOW__SMTP__SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${AIRFLOW__SMTP__SMTP_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "
        airflow scheduler & 
        exec airflow webserver
      "

volumes:
  mysql_data:
  airflow_logs:
