services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_DATABASE: pagespeed_db
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  airflow-init:
    image: apache/airflow:2.7.0-python3.10
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow:airflow@mysql:3306/pagespeed_db
      PAGESPEED_API_KEY: ${PAGESPEED_API_KEY}
      TARGET_URL: ${TARGET_URL}
    entrypoint: >
      bash -c "
        airflow db init &&
        airflow users create \
          --username devcharlie \
          --password Tony00642! \
          --firstname Charlie \
          --lastname Dev \
          --role Admin \
          --email devcharlie2698619@gmail.com
      "
    volumes:
      - ../dags:/opt/airflow/dags
      - ../plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - airflow_logs:/opt/airflow/logs

  airflow:
    image: apache/airflow:2.7.0-python3.10
    container_name: airflow
    restart: always
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow:airflow@mysql:3306/pagespeed_db
      PAGESPEED_API_KEY: ${PAGESPEED_API_KEY}
      TARGET_URL: ${TARGET_URL}
      AIRFLOW__SMTP__SMTP_HOST: ${AIRFLOW__SMTP__SMTP_HOST}
      AIRFLOW__SMTP__SMTP_STARTTLS: ${AIRFLOW__SMTP__SMTP_STARTTLS}
      AIRFLOW__SMTP__SMTP_SSL: ${AIRFLOW__SMTP__SMTP_SSL}
      AIRFLOW__SMTP__SMTP_PORT: ${AIRFLOW__SMTP__SMTP_PORT}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${AIRFLOW__SMTP__SMTP_MAIL_FROM}
      AIRFLOW__SMTP__SMTP_USER: ${AIRFLOW__SMTP__SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${AIRFLOW__SMTP__SMTP_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "
        airflow scheduler & 
        exec airflow webserver
      "

volumes:
  mysql_data:
  airflow_logs:
